data:
  nb_class_in_bag: 10
  bag_size: 50
  n_class: 31
  dim: 2048
  files:
    - ['amazon_amazon', 'amazon_dslr']
    - ['amazon_amazon','amazon_webcam']
    - ['dslr_dslr', 'dslr_amazon']
    - ['dslr_dslr', 'dslr_webcam']
    - ['webcam_webcam', 'webcam_amazon']
    - ['webcam_webcam', 'webcam_dslr']
model:
  dim_latent: 128
  n_hidden: 128
bagCSI:
  lr: 0.001
  n_epochs: 300
bagLME:
  lr: 0.001
  n_epochs: 300
  topk_fix: 15
  topk_lme: 31
  source_weight: 1
  ent_weight: 0.
  lmesource_weight: 1






























daLabelOT:  
  ent_weight: 0.
  clf_t_weight: 0
  div_weight: 0.
  n_epochs: 200
  epoch_start_g: 0
  start_align: 0
  use_div: False
  lr: 0.001
  lr_phi: 0.001
  #nblocks: 1
daLabelWD:  
  clf_t_weight: 0
  n_epochs: 30
  epoch_start_g: 0
  start_align: 1
  dist_loss_weight: 
    - 1
    - 0.1
    - 0.01
    - 0.001
    - 0.0001
  iter_domain_classifier: 2
  bag_loss_weight: 
    - 1
    - 25
    - 50
    - 100
  lr: 0.005


# tested
# small bag loss does not work (eg 0.1)
# larger bag loss works (eg 50) seems to work better
# with entropy loss, the model works better


