data:
  nb_class_in_bag: 10
  bag_size: 50
  n_class: 65
  dim: 2048
  files:
    - ['Art_Art', 'Art_Clipart']
    - ['Art_Art', 'Art_Product']
    - ['Art_Art', 'Art_RealWorld']
    - ['Clipart_Clipart', 'Clipart_Art']
    - ['Clipart_Clipart', 'Clipart_Product']
    - ['Clipart_Clipart', 'Clipart_RealWorld']
    - ['Product_Product', 'Product_Art']
    - ['Product_Product', 'Product_Clipart']
    - ['Product_Product', 'Product_RealWorld']
    - ['RealWorld_RealWorld', 'RealWorld_Art']
    - ['RealWorld_RealWorld', 'RealWorld_Clipart']
    - ['RealWorld_RealWorld', 'RealWorld_Product']
    
model:
  dim_latent: 128
  n_hidden: 128

bagCSI:
  lr: 0.001
  n_epochs: 300
  
bagLME:
  lr: 0.001
  n_epochs: 300
  topk_fix: 30
  topk_lme: 65
  source_weight: 1
  ent_weight: 0.
  lmesource_weight: 1

daLabelWD:  
  clf_t_weight: 0
  n_epochs: 300
  epoch_start_g: 0
  start_align: 21
  iter_domain_classifier: 2
  lr: 0.005
  dist_loss_weight: 
    - 0.001
    - 0.01
    - 0.1
    - 1
  bag_loss_weight:
    - 0.5
    - 1
    - 2




















daLabelOT:  
  ent_weight: 0.
  clf_t_weight: 0
  div_weight: 0.
  n_epochs: 200
  epoch_start_g: 0
  start_align: 0
  use_div: False
  lr: 0.001
  lr_phi: 0.001

