data:
  dep_sample: 1
  nb_class_in_bag: 10
  bag_size: 50
  n_class: 31
  dim: 2048
  files:
    - ['amazon_amazon', 'amazon_dslr']
    - ['amazon_amazon','amazon_webcam']
    - ['dslr_dslr', 'dslr_amazon']
    - ['dslr_dslr', 'dslr_webcam']
    - ['webcam_webcam', 'webcam_amazon']
    - ['webcam_webcam', 'webcam_dslr']
model:
  dim_latent: 128
  n_hidden: 128
bagCSI:
  lr: 0.001
  n_epochs: 30
  param_da:
    - 10
    - 1
    - 0.1
    - 0.01
    - 0.001
daLabelOT:  
  ent_weight: 0.
  clf_t_weight: 0
  div_weight: 0.
  n_epochs: 200
  epoch_start_g: 0
  start_align: 0
  use_div: False
  lr: 0.001
  lr_phi: 0.001
  #nblocks: 1
daLabelWD:  
  clf_t_weight: 0
  #div_weight: 0.
  n_epochs: 50
  epoch_start_g: 0
  start_align: 5
  #use_div: False
  #grad_scale: 1
  dist_loss_weight: 
    - 0.1
    - 0.01
    - 0.001
    - 0.0001
    - 0.00001
  iter_domain_classifier: 1
  bag_loss_weight:
    - 1
    - 10
    - 20
    - 30
    - 40
  lr: 0.01
  #lr_phi: 0.001
  #nblocks: 1



