data:
  nb_class_in_bag: 10
  bag_size: 50
  dim: 2
  variance: 2
  n_class: 3
model:
  dim_latent: 512
  n_hidden: 512
bagCSI:
  lr: 0.001
  n_epochs: 200
bagLME:
  lr: 0.001
  n_epochs: 30
  topk_fix: 1
  topk_lme: 10
  source_weight: 1
  ent_weight: 0.
  lmesource_weight: 1
  lmesource_weight: 1


