data:
  nb_class_in_bag: 10
  bag_size: 50
  n_class: 10
model:
  dim_latent: 128
  n_hidden: 128
bagCSI:
  lr: 0.001
  n_epochs: 30
bagLME:
  lr: 0.001
  n_epochs: 30
  topk_fix: 1
  topk_lme: 1
  source_weight: 1
  ent_weight: 0
  lmesource_weight: 1

daLabelWD:  
n_epochs: 30
epoch_start_g: 0
start_align: 2
iter_domain_classifier: 2
lr: 0.001
dist_loss_weight: 
  - 0.1
  - 0.5
  - 1
  - 2
bag_loss_weight:
  - 0.5
  - 1
  - 2




















daLabelOT:  
  ent_weight: 0.
  clf_t_weight: 0
  div_weight: 0.
  n_epochs: 200
  epoch_start_g: 0
  start_align: 0
  use_div: False
  lr: 0.001
  lr_phi: 0.001
  #nblocks: 1


